{% set name = "pqdm" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pqdm-{{ version }}.tar.gz
  sha256: d99d01fe498d327b440ebfe08c14c84e0dc9ecce6172ef9a31f96bb1aaf4e9e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - bounded-pool-executor
    - python >=3.6
    - tqdm
    - typing-extensions

test:
  imports:
    - pqdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/niedakh/pqdm
  summary: PQDM is a TQDM and concurrent futures wrapper to allow enjoyable paralellization of progress bars.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rsignell-usgs
